sudo: false
language: go
go:
  - 1.10.x
  - 1.x

# only last commit
git:
  depth: 1

# use vendor dependencys
install: true

notifications:
  email: false

before_install:
  - go get -u golang.org/x/lint/golint
  - go get github.com/fzipp/gocyclo
  - go get github.com/gordonklaus/ineffassign
  - go get -u github.com/client9/misspell/cmd/misspell

script: 
  - golint .
  - golint examples/
  - go test -v -race .
  - go test -v -race examples/
  - go vet -v .
  - go vet -v examples/
  - gocyclo .
  - gocyclo examples/
  - ineffassign .
  - ineffassign examples/
  - misspell *.go
  - misspell examples/
