sudo: false
language: go
go:
  - 1.10.x
  - 1.x

# only last commit
git:
  depth: 1

# use vendor dependencys
install: true

notifications:
  email: false

env:
  - GO111MODULE="on"

before_install:
  - go get -u golang.org/x/lint/golint
  - go get github.com/fzipp/gocyclo
  - go get github.com/gordonklaus/ineffassign
  - go get -u github.com/client9/misspell/cmd/misspell

script: 
  - golint `go list`
  - golint ./examples/*.go
  - go test -v -race `go list`
  - go test -v -race ./examples/*.go
  - go vet -v `go list`
  - go vet -v ./examples/*.go
  - gocyclo *.go
  - gocyclo ./examples/*.go
  - ineffassign *.go
  - ineffassign ./examples/*.go
  - misspell *.go
  - misspell ./examples/*.go
