sudo: false
language: go
go:
  - 1.10.x
  - 1.x

# only last commit
git:
  depth: 1

# use vendor dependencys
install: true

notifications:
  email: false

script: 
  - golint .
  - golint examples/
  - go test -v -race ./...
  - go vet -v ./...
  - gocyclo .
  - gocyclo examples/
  - ineffassign .
  - misspell *.go
  - misspell examples/
